version: "3.1"

services:
  vozdb:
    image: postgres
    restart: always
    ports:
      - "5423:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
#  shared:
#    image: nginx
#    ports:
#      - "5551:80"
#    volumes:
#      - ./data/:/usr/share/nginx/html
#      - ./.dev/conf.d:/etc/nginx/conf.d

  worker:
    build:
      context: .
    container_name: crawler_worker
    restart: always
    ports:
      - '5001:5000'
    links:
      - vozdb
    environment:
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DATABASE=${POSTGRES_DB}
      - PG_HOST=vozdb
      - PG_PORT=5432
    volumes:
      - ./:/usr/src/app/
volumes:
  pgdata:
