version: "3.1"

networks:
  backend:
    internal: true

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5423:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  worker:
    build:
      context: ./services/scrapy
    restart: always
    ports:
      - '5001:5000'
      - '6800:6800'
    links:
      - db
    networks:
      - backend
    environment:
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DATABASE=${POSTGRES_DB}
      - PG_HOST=db
      - PG_PORT=5432
    volumes:
      - ./services/scrapy:/usr/src/app/

volumes:
  pgdata:
