version: "3.1"

services:
  vozdb:
    image: postgres
    restart: always
    ports:
      - "5423:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  scrapy:
    build:
      context: services/scrapy
    container_name: crawler_worker
    restart: always
    ports:
      - '5001:5000'
      - '6800:6800'
    links:
      - vozdb
    environment:
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DATABASE=${POSTGRES_DB}
      - PG_HOST=vozdb
      - PG_PORT=5432
    volumes:
      - ./services/scrapy:/usr/src/app/
volumes:
  pgdata:
