version: "3.1"

services:
  vozdb:
    image: postgres
    restart: always
    ports:
      - "5423:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
    volumes:
      - pgdata:/var/lib/postgresql/data
#  shared:
#    image: nginx
#    ports:
#      - "5551:80"
#    volumes:
#      - ./data/:/usr/share/nginx/html
#      - ./.dev/conf.d:/etc/nginx/conf.d

  worker:
    build:
      context: .
    container_name: crawler_worker
    ports:
      - '5001:5000'
    links:
      - vozdb
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=abcd1234
      - PG_DATABASE=postgres
      - PG_HOST=vozdb
      - PG_PORT=5423
      - NGINX_HOST=shared
      - NGINX_PORT=80
    volumes:
      - ./:/usr/src/app/
volumes:
  pgdata:
