version: "3.1"

services:
  vozdb:
    image: postgres
    restart: always
    ports:
      - 2345:5432
    environment:
      POSTGRES_PASSWORD: abcd1234
    volumes:
      - pgdata:/var/lib/postgresql/data
  shared:
    image: nginx
    ports:
      - 5551:80
    volumes:
      - ./data/:/usr/share/nginx/html
      - ./.dev/conf.d:/etc/nginx/conf.d

  worker:
    build:
      context: .
    container_name: crawler_worker
    ports:
      - '5000:5000'
    links:
      - vozdb
      - shared
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=abcd1234
      - PG_DATABASE=postgres
      - PG_HOST=0.0.0.0
      - PG_PORT=5432
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - REDIS_HOST=localhost
volumes:
  pgdata:
