version: "3.1"

networks:
  backend:
    driver: overlay

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5423:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  scrapy:
    build:
      context: ./services/scrapy
    restart: always
    ports:
      - '5001:5000'
      - '6800:6800'
    links:
      - db
    networks:
      - backend
    environment:
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DATABASE=${POSTGRES_DB}
      - PG_HOST=db
      - PG_PORT=5432
    volumes:
      - ./services/scrapy:/usr/src/app/

  scrapyd:
    build:
      context: ./services/scrapyd
    ports:
      - "127.0.0.1:6800:6800"
    volumes:
      - ./scrapyd:/var/lib/scrapyd
    restart: always
    links:
      - db
      - scrapy
    networks:
      - backend

  scrapyrt:
    build:
      context: ./services/scrapyd
#    image: scrapyd-onbuild
    command: scrapyrt -i 0.0.0.0 -p 9080
    ports:
      - "127.0.0.1:9080:9080"
    volumes:
      - ./services/scrapyrt:/data
    working_dir: /data
    links:
      - db
      - scrapy
      - scrapyd
    restart: always
    networks:
      - backend

volumes:
  pgdata:
