version: "3.1"

networks:
  backend:
    internal: true

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5423:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

#  worker:
#    build:
#      context: ./services/scrapy
#    restart: always
#    ports:
#      - '5001:5000'
#      - '6800:6800'
#    links:
#      - db
#    networks:
#      - backend
#    environment:
#      - PG_USER=${POSTGRES_USER}
#      - PG_PASSWORD=${POSTGRES_PASSWORD}
#      - PG_DATABASE=${POSTGRES_DB}
#      - PG_HOST=db
#      - PG_PORT=5432
#    volumes:
#      - ./services/scrapy:/usr/src/app/

  scrapyd:
#    image: easypi/scrapyd
    build:
      context: ./services/scrapyd
    ports:
      - "6800:6800"
    volumes:
      - ./data:/var/lib/scrapyd
#      - /usr/local/lib/python3.11/dist-packages
    restart: unless-stopped

  scrapy:
#    image: easypi/scrapyd
    build:
      context: ./services/scrapyd
    command: bash
    volumes:
      - ./services/scrapyd:/code
    working_dir: /code
    restart: unless-stopped

  scrapyrt:
#    image: easypi/scrapyd
    build:
      context: ./services/scrapyd
    command: scrapyrt -i 0.0.0.0 -p 9080
    ports:
      - "9080:9080"
    volumes:
      - ./services/scrapyd:/code
    working_dir: /code
    restart: unless-stopped
volumes:
  pgdata:
